test_that("km.curve yileds the same outputs as survfit", {
  library(survival)
  library(Rcpp)
  df_test <- createTestData(200, 2, first_zero=TRUE, last_zero=FALSE, subset_present=FALSE, logical_strata=FALSE, na_strata=TRUE)
  e <- survfit(Surv(t, d)~strata, df_test, weight=w, na.action=na.omit, conf.type = "none")
  t <- km.curve(Surv(t, d)~strata, df_test, weight="w", na.action=na.omit, conf.type = "none")
  expected <- as.numeric(c(e$time, e$surv, e$n, e$n.risk, e$n.event, e$n.censor, e$std.err, e$low, e$high, e$strata))
  tested <- as.numeric(c(t$time, t$surv, t$n, t$n.risk, t$n.event, t$n.censor, t$std.err, t$low, t$high, t$strata))
  expect_equal(expected, tested)
})

test_that("km.curve yileds the same outputs as survfit", {
  library(survival)
  library(Rcpp)
  df_test <- createTestData(200, 1, first_zero=FALSE, last_zero=TRUE, subset_present=FALSE, logical_strata=TRUE, na_strata=FALSE)
  e <- survfit(Surv(t, d)~strata, df_test, weight=w, conf.type = "none")
  t <- km.curve(Surv(t, d)~strata, df_test, weight="w", conf.type = "none")
  expected <- as.numeric(c(e$time, e$surv, e$n, e$n.risk, e$n.event, e$n.censor, e$std.err, e$low, e$high, e$strata))
  tested <- as.numeric(c(t$time, t$surv, t$n, t$n.risk, t$n.event, t$n.censor, t$std.err, t$low, t$high, t$strata))
  expect_equal(expected, tested)
})
